version: "3.8"
services:
  db:
    image: postgres:15.2
    restart: always
    container_name: loans_postgre
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  broker:
    image: rabbitmq:3-management
    restart: unless-stopped
    container_name: loans_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672